name: otel

services:  
  otel:
    profiles: [all, otel]
    networks:
      - otel
    ports:
      - 14317:4317
      - 14318:4318
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    volumes:
      - "./otel/otel-collector-config.yaml:/conf/otel-collector-config.yaml"

  jaeger:
    profiles: [all, otel]
    networks:
      - otel
    image: jaegertracing/all-in-one:1
    ports:
      - 16687:16686
    depends_on:
      - otel

  redis:
    profiles: [all, db]
    networks:
      - otel
    image: bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  python:
    profiles: [all, apps]
    networks:
      - otel
    build:
      dockerfile: ./app/python/Containerfile
    environment:
      - PORT=8000
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_RESOURCE_ATTRIBUTES=team=dev,cluster-name=local,env=dev
      - OTEL_SERVICE_NAME=python-otlp
    ports:
      - 8000:8000
    depends_on:
      - otel

  go:
    profiles: [all, apps]
    networks:
      - otel
    build:
      dockerfile: ./app/go/Containerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_RESOURCE_ATTRIBUTES=team=dev,cluster-name=local,env=dev
      - OTEL_SERVICE_NAME=go-otlp
      - REDIS_URL=redis:6379
    ports:
      - 8001:8001
    depends_on:
      - otel


networks:
  otel:
    name: "otel"